"""attendance attendance_type attendance_grade

Revision ID: 004ff5a83d08
Revises: b35eec6882bd
Create Date: 2023-04-20 16:13:47.838759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004ff5a83d08'
down_revision = 'b35eec6882bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_type',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_type'))
    )
    op.create_table('attendance',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_attendance_group_id_group')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_attendance_subject_id_subject')),
    sa.ForeignKeyConstraint(['type_id'], ['attendance_type.id'], name=op.f('fk_attendance_type_id_attendance_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance'))
    )
    op.create_table('attendance_grade',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('attendance_id', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], name=op.f('fk_attendance_grade_attendance_id_attendance')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_attendance_grade_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_grade'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_grade')
    op.drop_table('attendance')
    op.drop_table('attendance_type')
    # ### end Alembic commands ###
