"""adding activity's tables

Revision ID: 07b2ea541264
Revises: 08f1c418a206
Create Date: 2023-11-21 12:28:30.783886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b2ea541264'
down_revision = '08f1c418a206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_sub_type',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_sub_type'))
    )
    op.create_table('activity_type',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_type'))
    )
    op.create_table('rate_activity',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('activity_type_id', sa.String(length=32), nullable=False),
    sa.Column('activity_sub_type_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['activity_sub_type_id'], ['activity_sub_type.id'], name=op.f('fk_rate_activity_activity_sub_type_id_activity_sub_type')),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_type.id'], name=op.f('fk_rate_activity_activity_type_id_activity_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_activity'))
    )
    op.create_table('activity',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('file', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=240), nullable=True),
    sa.Column('type_id', sa.String(length=32), nullable=False),
    sa.Column('rate_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['rate_id'], ['rate_activity.id'], name=op.f('fk_activity_rate_id_rate_activity')),
    sa.ForeignKeyConstraint(['type_id'], ['activity_type.id'], name=op.f('fk_activity_type_id_activity_type')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_activity_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('rate_activity')
    op.drop_table('activity_type')
    op.drop_table('activity_sub_type')
    # ### end Alembic commands ###
