"""add tables for labs

Revision ID: 08f1c418a206
Revises: 004ff5a83d08
Create Date: 2023-06-29 17:09:35.642988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f1c418a206'
down_revision = '004ff5a83d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_lab_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab'))
    )
    op.create_table('labs_grade',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lab_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], name=op.f('fk_labs_grade_lab_id_lab')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_labs_grade_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labs_grade'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labs_grade')
    op.drop_table('lab')
    # ### end Alembic commands ###
