"""add table group

Revision ID: 94d17cc8ee11
Revises: de3ad24014b8
Create Date: 2022-12-05 23:35:22.756901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d17cc8ee11'
down_revision = 'de3ad24014b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_group_id_group'), 'group', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_group_id_group'), type_='foreignkey')
        batch_op.drop_column('group_id')

    op.drop_table('group')
    # ### end Alembic commands ###
