"""add tables for grade

Revision ID: b35eec6882bd
Revises: 1a1ed2a7f63c
Create Date: 2022-12-20 00:47:23.633413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35eec6882bd'
down_revision = '1a1ed2a7f63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_grade',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_type_grade'))
    )
    op.create_table('grade',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_grade_subject_id_subject')),
    sa.ForeignKeyConstraint(['type_id'], ['type_grade.id'], name=op.f('fk_grade_type_id_type_grade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade'))
    )
    op.create_table('grade_users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('grade_id', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], name=op.f('fk_grade_users_grade_id_grade')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_grade_users_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_users')
    op.drop_table('grade')
    op.drop_table('type_grade')
    # ### end Alembic commands ###
