"""add role_id

Revision ID: d4379f1bf181
Revises: 
Create Date: 2022-11-25 15:06:32.356539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4379f1bf181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklisted_token', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_blacklisted_token_token'), ['token'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_login'), ['login'])
        batch_op.create_foreign_key(batch_op.f('fk_user_role_id_role'), 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_role_id_role'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_user_login'), type_='unique')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('blacklisted_token', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_blacklisted_token_token'), type_='unique')

    # ### end Alembic commands ###
